FROM python:3.8-slim-buster

WORKDIR /app

RUN apt-get update
RUN apt-get -y install gcc
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY plants_manager plants_manager
COPY uwsgi.ini .

ENV PYTHONPATH "${PYTHONPATH}:/app"

CMD ["uwsgi", "uwsgi.ini"]
